// frontend/src/App.tsx
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';

function App() {
  return (
    <Router>
      <div className="min-h-screen bg-haunted-dark text-white">
        <header className="p-6 border-b border-haunted-purple">
          <h1 className="text-4xl font-spooky text-haunted-orange">
            👻 Haunted Home Orchestrator
          </h1>
        </header>
        <main className="container mx-auto p-6">
          <Routes>
            <Route path="/" element={<HomePage />} />
          </Routes>
        </main>
      </div>
    </Router>
  );
}

function HomePage() {
  return (
    <div className="text-center py-20">
      <h2 className="text-3xl font-spooky text-haunted-purple mb-4">
        Welcome to the Haunted Home
      </h2>
      <p className="text-xl text-gray-300">
        Transform your smart home into a spooky experience
      </p>
      <div className="mt-8">
        <button className="bg-haunted-orange hover:bg-orange-700 text-white font-bold py-3 px-6 rounded-lg transition-colors">
          Get Started
        </button>
      </div>
    </div>
  );
}

export default App;

// frontend/src/App.vue
<template>
  <div class="dark-mode min-h-screen">
    <header class="border-b border-purple-900/50 bg-zinc-900/50 backdrop-blur-sm sticky top-0 z-50">
      <div class="container mx-auto px-6 py-4">
        <div class="flex items-center justify-between">
          <h1 class="text-4xl font-spooky text-orange-500 flex items-center gap-3">
            <i class="pi pi-moon text-3xl animate-float"></i>
            Haunted Home Orchestrator
          </h1>
          <div v-if="isAuthenticated" class="flex items-center gap-4">
            <span class="text-gray-300">{{ userEmail }}</span>
            <Button 
              label="Logout" 
              icon="pi pi-sign-out" 
              severity="secondary" 
              text 
              @click="logout"
            />
          </div>
        </div>
      </div>
    </header>

    <main class="container mx-auto px-6 py-8">
      <router-view />
    </main>

    <footer class="mt-16 border-t border-purple-900/50 py-6">
      <div class="container mx-auto px-6 text-center text-gray-400">
        <p class="flex items-center justify-center gap-2">
          <i class="pi pi-bolt animate-flicker"></i>
          Powered by AI & OpenRouter
          <i class="pi pi-bolt animate-flicker"></i>
        </p>
      </div>
    </footer>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import Button from 'primevue/button'
import { useAuth } from './composables/useAuth'

const router = useRouter()
const { isAuthenticated, userEmail, logout: authLogout } = useAuth()

const logout = async () => {
  await authLogout()
  router.push('/login')
}
</script>
